package iotprojectmanagementforuniversity;
//import com.sun.jdi.connect.spi.Connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
//import javax.swing.JOptionPane;
public class AddTeacher1 extends javax.swing.JFrame implements ActionListener{

    private Object DriverManager;

    /**
     * Creates new form AddTeacher1
     */   
    public AddTeacher1() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTeacher = new javax.swing.JTextField();
        Teachername1 = new javax.swing.JLabel();
        TeacherContact = new javax.swing.JLabel();
        txtTeachercont = new javax.swing.JTextField();
        TeacherContact1 = new javax.swing.JLabel();
        txtTeacheremail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TeacherAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        TeacherSubject = new javax.swing.JLabel();
        txtTeachersub = new javax.swing.JTextField();
        TeacherCollege = new javax.swing.JLabel();
        txtTeacherCollege = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDeleteStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        btnCopyStudent = new javax.swing.JButton();
        btnSaveStudent = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        TeacherClgId = new javax.swing.JLabel();
        txtcollegeid = new javax.swing.JTextField();
        btnSaveStudent1 = new javax.swing.JButton();
        TeacherDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        Teachername1.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        Teachername1.setText("Teacher-name :-");

        TeacherContact.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        TeacherContact.setText("Teacher-Contact :-");

        TeacherContact1.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        TeacherContact1.setText("Teacher-Email :-");

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Calisto MT", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("                                                                                                   --: NEW-TEACHER-DETAILS:--");

        TeacherAddress.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        TeacherAddress.setText("Teacher-Address :-");

        TeacherSubject.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        TeacherSubject.setText("Teacher-Subject :-");

        TeacherCollege.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        TeacherCollege.setText("Teacher-College :-");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnDeleteStudent.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteStudent.setFont(new java.awt.Font("Footlight MT Light", 3, 18)); // NOI18N
        btnDeleteStudent.setText("Delete");
        btnDeleteStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 4, true));
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });

        btnEditStudent.setBackground(new java.awt.Color(255, 204, 204));
        btnEditStudent.setFont(new java.awt.Font("Footlight MT Light", 3, 18)); // NOI18N
        btnEditStudent.setText("Edit");
        btnEditStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 4, true));
        btnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStudentActionPerformed(evt);
            }
        });

        btnCopyStudent.setBackground(java.awt.Color.magenta);
        btnCopyStudent.setFont(new java.awt.Font("Footlight MT Light", 3, 18)); // NOI18N
        btnCopyStudent.setText("Copy");
        btnCopyStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 4, true));
        btnCopyStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyStudentActionPerformed(evt);
            }
        });

        btnSaveStudent.setBackground(new java.awt.Color(255, 102, 79));
        btnSaveStudent.setFont(new java.awt.Font("Footlight MT Light", 3, 18)); // NOI18N
        btnSaveStudent.setText("Student-info");
        btnSaveStudent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 4, true));
        btnSaveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStudentActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(51, 51, 255));
        btnCancel.setFont(new java.awt.Font("Footlight MT Light", 3, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 4, true));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        TeacherClgId.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        TeacherClgId.setText("Teacher-college-id :-");

        btnSaveStudent1.setBackground(new java.awt.Color(102, 255, 102));
        btnSaveStudent1.setFont(new java.awt.Font("Footlight MT Light", 3, 18)); // NOI18N
        btnSaveStudent1.setText("Save");
        btnSaveStudent1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 4, true));
        btnSaveStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveStudent1ActionPerformed(evt);
            }
        });

        TeacherDOB.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        TeacherDOB.setText("Teacher-DOB :-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Teachername1)
                                .addGap(39, 39, 39)
                                .addComponent(txtTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TeacherAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(TeacherClgId))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcollegeid, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeacherContact)
                            .addComponent(TeacherSubject, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TeacherDOB)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnCopyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTeachercont, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(txtTeachersub)
                            .addComponent(txtDOB))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TeacherCollege)
                            .addComponent(TeacherContact1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTeacheremail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeacherCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnSaveStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(btnSaveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(391, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherContact, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherContact1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeacheremail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeachercont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Teachername1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeachersub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTeacherCollege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeacherSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeacherClgId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcollegeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeacherDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveStudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCopyStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void btnCopyStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCopyStudentActionPerformed

    private void btnSaveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStudentActionPerformed
     
        
     /*   if(txtTeacher.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this,"Please Enter your Name");
            txtTeacher.setText("");
            txtTeacher.grabFocus();
        }
        else if(txtTeachercont.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this,"Please Enter Contact");
            txtTeachercont.setText("");
            txtTeachercont.grabFocus();
        }
        /*else if(txtBranch.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this,"Please Enter Branch");
            txtBranch.setText("");
            txtBranch.grabFocus();
        }*/
        /*else  if(txtSemester.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this,"Please Enter Semester");
            txtSemester.setText("");
            txtSemester.grabFocus();
        }
        else if(txtAddress.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this,"Please your Enter Address");
            txtAddress.setText("");
            txtAddress.grabFocus();
        }
       else if(txtTeachersub.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this,"Please Enter Teacher subject name");
           txtTeachersub.setText("");
            txtTeachersub.grabFocus();
        }
        else  if(txtTeacheremail.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this,"Please Enter Email Address");
            txtTeacheremail.setText("");
            txtTeacheremail.grabFocus();
        }
       else if(txtDOB.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this,"Please Enter your DOB");
            txtDOB.setText("");
            txtDOB.grabFocus();
        }
        else{
            Connection c;
            try {

                String UserName=txtTeacher.getText();
                //String FatherName=txtfather1.getText();
                @SuppressWarnings("LocalVariableHidesMemberVariable")
                String Contactno=txtTeachercont.getText();//if i convert it into in integer then i will do String Contactno=Integer.parseInt(txtContact.getText());
                String Email=txtTeacheremail.getText();
                //String HomeContact=txtHContactno.getText();
                @SuppressWarnings("LocalVariableHidesMemberVariable")
                //String Branch=txtBranch.getText();
                //@SuppressWarnings("LocalVariableHidesMemberVariable")
                //String Semester=txtSemester.getText();
               // @SuppressWarnings("LocalVariableHidesMemberVariable")
                String Address=txtAddress.getText();
                @SuppressWarnings("LocalVariableHidesMemberVariable")
                //String DOB=txtDOB.getText();

                Class.forName("com.mysql.cj.jdbc.Driver");
                Conn con = new Conn();
                //c = DriverManager.getConnection("jdbc:mysql:///IOTPROJECTMANAGEMENTSYSTEM","root","Lucky@1234");
                var s=c.prepareStatement("insert into attendencestudentdetails4(UserName,Contactno,Email,Teachersub,Address,DoB)");
                // String query="insert into login where attendencestudentdetails4(UserName,FatherName,Contactno,Email,HomeContact,Branch,Semester,Address,Dob);
                s.setString(1, UserName);
                //s.setString(2, FatherName);
                s.setString(2, Contactno);
                s.setString(3, Email);
                s.setString(4, Teachersub);
                //s.setString(6, Branch);
                //s.setString(7, Semester);
                s.setString(5, Address);
               s.setString(6,  DOB);
                s.executeUpdate();
                JOptionPane.showMessageDialog(this, "your data is saved successfully","success",JOptionPane.INFORMATION_MESSAGE);

                txtTeacher.setText("");
                txtTeachersub.setText("");
                txtTeachercont.setText("");
                txtTeacheremail.setText("");
                //txtHContactno.setText("");
                //txtBranch.setText("");
                //txtSemester.setText("");
                txtAddress.setText("");
                txtDOB.setText("");

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmAddNewStudent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmAddNewStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/

    }//GEN-LAST:event_btnSaveStudentActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveStudent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveStudent1ActionPerformed
     
    /**
     * @param args the command line arguments
     */
               
    
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeacher1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeacher1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeacher1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeacher1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @SuppressWarnings("override")
            public void run() {
                new AddTeacher1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TeacherAddress;
    private javax.swing.JLabel TeacherClgId;
    private javax.swing.JLabel TeacherCollege;
    private javax.swing.JLabel TeacherContact;
    private javax.swing.JLabel TeacherContact1;
    private javax.swing.JLabel TeacherDOB;
    private javax.swing.JLabel TeacherSubject;
    private javax.swing.JLabel Teachername1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCopyStudent;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnSaveStudent;
    private javax.swing.JButton btnSaveStudent1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtTeacher;
    private javax.swing.JTextField txtTeacherCollege;
    private javax.swing.JTextField txtTeachercont;
    private javax.swing.JTextField txtTeacheremail;
    private javax.swing.JTextField txtTeachersub;
    private javax.swing.JTextField txtcollegeid;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
